### ISSUE TITLE
[Support]: Database error after updating to 2.2.0 as running a home assistant addon

### ISSUE THREAD

**Issue by kinnujan** [NickM-27/swatch#33]
### Describe the problem you are having

Hi! Trying to test this, but just updated and now it wont start. Gives error related to database? I'm running inside home assistant and as a ad don. Wonder if it is related to that?

### Version

2.2.0

### Swatch config file

```yaml
# REQUIRED: Define list of cameras that will be used for color detection.
cameras:
  # REQUIRED: Name of the camera
  autokatos:
    # OPTIONAL: Frequency in seconds to run detection on the camera.
    # a value of 0 disables auto detection (Default: shown below).
    auto_detect: 10
    # OPTIONAL: Configure the url and retention of snapshots. (Default: Shown Below)
    snapshot_config:
        # OPTIONAL: but highly recommended, setting the default url for a snapshot to be
        # processed by this camera. This is required for auto detection (Default: none).
        url: "http://xxxx/cgi-bin/api.cgi?cmd=Snap&channel=6&rs=qwerty&user=xxxxx&password=xxxx"
        # OPTIONAL: Whether or not to save the snapshots of confirmed detections (Default: shown below).
        save_detections: true
        # OPTIONAL: Whether or not to save the snapshots of missed detections (Default: shown below).
        save_misses: true
        # OPTIONAL: Variations of snapshots to keep. Options are all, mask, crop (Default: shown below).
        mode: "all"
        # OPTIONAL: Number of days of snapshots to keep (Default: shown below).
        retain_days: 7
    # REQUIRED: Zones are cropped areas where the object can be expected to be.
    # This makes searching / matches for efficient and more predictable than searching
    # the entire image.
    zones:
      # REQUIRED: Name of the zone.
      vasenpuoli:
        # REQUIRED: Coordinates to crop the zone by.
        # NOTE: The order of the coordinates are: y, y+h, x, x+w starting in the top left corner as 0, 0.
        coordinates: 0,500,0,500
        # REQUIRED: List of objects that may be in this zone. These correspond to
        # the objects list defined previously and are matched by name.
        objects:
          - fiat
# REQUIRED: Define a list of objects that are expected to be seen. These can be specific
# to one camera or common between many / all cameras
objects:
  # REQUIRED: Name of the object
  fiat:
    # REQUIRED: the list of color variants that this object can be detected as. Useful for
    # different lighting conditions
    color_variants:
      name_of_variant:
        color_lower: 6, 21, 79
        color_upper: 255, 132, 252
        # OPTIONAL: the time range for when this color variant is allowed
        # NOTE: make sure that /etc/localtime is passed to the container so it has valid time
        #time_range:
          # OPTIONAL: Color variant is valid if current time is > this 24H time (Default: shown below).
          #after: "00:00"
          # OPTIONAL: Color variant is valid if current time is < this 24H time (Default: shown below).
          #before: "24:00"
    # OPTIONAL: the min number of pixels with R, G, B values within the bounds to be
    # considered a true positive. This is recommended to be set as a super small amount
    # could be a false positive. (Default: shown below)
    #min_area: 1000
    # OPTIONAL: the max number of pixels with R, G, B values within the bounds to be
    # considered a true positive (Default: shown below).
    #max_area: 100000
```

### Relevant log output

```shell
Starting SwatchApp
Importing SwatchApp Config
Verified SwatchApp Config
Starting migrations
There is nothing to migrate
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/playhouse/sqliteq.py", line 266, in run
    writer.run()
  File "/usr/local/lib/python3.10/site-packages/playhouse/sqliteq.py", line 128, in run
    conn = self.database.connection()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3153, in connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
Starting Auto Detection for autokatos
Starting snapshot cleanup
Starting Detection Cleanup
```

**Comment by NickM-27** [comment]
Definitely related to the addon. If you go into home assistant /media directory do you see any `swatch.db` file ?

**Comment by kinnujan** [comment]
Yes, it is there.

**Comment by NickM-27** [comment]
> Yes, it is there.

Interesting that it is there, do you see a /swatch directory under media as well?

I think the issue may be that the addon I had the path as `/media/swatch.db` but I don't think it has permissions for that or there could be some other issue. The path most likely needs to be `/media/swatch/swatch.db`. I just put an update for the addon so that should be available and hopefully fix it.

**Comment by backslashV** [comment]
FYI, this issue is still there on v2.2.2.

**Comment by NickM-27** [comment]
Thanks for your patience, this is fixed with 2.2.3

**Comment by kinnujan** [comment]
Tried 2.2.3, but it still there. Here is log, if it helps:

> [2022-05-27 21:09:59,313]: INFO - Starting SwatchApp
[2022-05-27 21:09:59,319]: INFO - Importing SwatchApp Config
[2022-05-27 21:09:59,319]: INFO - Verified SwatchApp Config
Starting migrations
[2022-05-27 21:09:59,324]: INFO - Starting migrations
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/swatch/swatch/__main__.py", line 14, in <module>
    swatch_app = SwatchApp()
  File "/opt/swatch/swatch/app.py", line 41, in __init__
    self.__init_db__()
  File "/opt/swatch/swatch/app.py", line 66, in __init_db__
    router.run()
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 201, in run
    diff = self.diff
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 75, in diff
    done = set(self.done)
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 70, in done
    return [mm.name for mm in self.model.select().order_by(self.model.id)]
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/peewee_migrate/router.py", line 59, in model
    MigrateHistory.create_table(True)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6758, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 5861, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 5716, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3190, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3174, in execute_sql
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3175, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3159, in cursor
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3112, in connect
    with __exception_wrapper__:
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3113, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3453, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

**Comment by NickM-27** [comment]
Do you see a db file in `/media/swatch/swatch.db` ?

**Comment by kinnujan** [comment]
No, and no /swatch/ -folder in /media/.

**Comment by NickM-27** [comment]
Okay, are you able to create /media/swatch/ directory and then try again? Perhaps it is failing because the directory doesn't exist

**Comment by kinnujan** [comment]
That worked!
