### ISSUE TITLE
[Support]: Possible Config Issues/ No Detections Firing

### ISSUE THREAD

**Issue by ssryan9** [NickM-27/swatch#46]
### Describe the problem you are having

I've setup a zone that crops my image down to this:
<img width="123" alt="Screen Shot 2022-06-08 at 10 32 21 PM" src="https://user-images.githubusercontent.com/54726620/172751774-31c3130e-c202-4f44-b609-f4794a553bf3.png">

In the config file you'll see the color variant I've setup (color_lower: 0, 0, 150, color_upper: 255, 130, 255)

I've not seen any detections triggered. Do I have the color variant range setup correctly? I've triggered new snapshots that contain the same amount of color as the image above.

Logs were sparse

### Version

3.0.3

### Swatch config file

```yaml
objects:
  water_meter:
    color_variants:
      default:
        color_lower: 0, 0, 150
        color_upper: 255, 130, 255
    
cameras:
  BB_Camera:
    snapshot_config:
        url: "http://HA/lastimage.jpeg"
    zones:
      full_view:
        coordinates: 225, 25, 360, 360
        objects:
          - water_meter
      water_needed:
        coordinates: 300, 300, 365, 360
        objects:
          - water_meter
```

### Relevant log output

```shell
[2022-06-08 22:32:03,141]: INFO - Starting SwatchApp
[2022-06-08 22:32:03,150]: INFO - Importing SwatchApp Config
[2022-06-08 22:32:03,150]: INFO - Verified SwatchApp Config
Starting migrations
[2022-06-08 22:32:03,154]: INFO - Starting migrations
There is nothing to migrate
[2022-06-08 22:32:03,164]: INFO - There is nothing to migrate
[2022-06-08 22:32:03,166]: INFO - Starting snapshot cleanup
[2022-06-08 22:32:03,166]: INFO - Starting Detection Cleanup
```

### Any other information that may be helpful

Thanks in advance - really excited about getting this across the finish line

**Comment by NickM-27** [comment]
I don't see min_area defined, default value is 1000 and that looks like it will need to be lowered a lot (maybe try 0 just to see what happens, but that's generally not recommended)

**Comment by ssryan9** [comment]
Still getting nothing despite adding min_area. Currently have it set at 0

objects:
  water_meter:
    color_variants:
      default:
        color_lower: 0, 0, 150
        color_upper: 255, 130, 255
    min_area: 0
cameras:
  BB_Camera:
    snapshot_config:
        url: "http://HA/last_event.jpeg"
    zones:
      full_view:
        coordinates: 225, 25, 360, 360
        objects:
          - water_meter
      water_needed:
        coordinates: 300, 300, 365, 360
        objects:
          - water_meter

**Comment by NickM-27** [comment]
Did you use the color playground to get those color values?

**Comment by ssryan9** [comment]
Yes I did. I can give it another shot

**Comment by ssryan9** [comment]
That did the trick - don't know how I missed it. Thank you!!

**Comment by ssryan9** [comment]
> Every 30 seconds or when the detect service is manually run through HA. It uses host:4500/api/all/latest when checking every 30 seconds

The sensor is not updating when the object is removed from the frame.

Updated to the newly released version and now getting this error:
[2022-06-09 10:39:30,724]: INFO - Starting SwatchApp
[2022-06-09 10:39:30,735]: INFO - Importing SwatchApp Config
[2022-06-09 10:39:30,735]: INFO - Verified SwatchApp Config
Starting migrations
[2022-06-09 10:39:30,743]: INFO - Starting migrations
There is nothing to migrate
[2022-06-09 10:39:30,758]: INFO - There is nothing to migrate
[2022-06-09 10:39:30,762]: INFO - Starting Auto Detection for BB_Camera
[2022-06-09 10:39:30,763]: INFO - Starting snapshot cleanup
[2022-06-09 10:39:30,764]: INFO - Starting Detection Cleanup
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/swatch/swatch/detection.py", line 125, in run
    self.__handle_detections__(result)
  File "/opt/swatch/swatch/detection.py", line 111, in __handle_detections__
    if object_result["result"]:
KeyError: 'result'

**Comment by NickM-27** [comment]
3.0.4 should be working

**Comment by ssryan9** [comment]
Yep it's fixed now. Thank you!
